[WIP] doc: add configuration example for nvim with blink
wlh320/rime-ls pull request #46
Opened 2024-12-22 11:18 UTC by Kaiser-Yang

2024-12-22 12:07 UTC, Kaiser-Yang commented
@wlh320 Finished.

2024-12-22 12:10 UTC, Kaiser-Yang commented
注意 `blink.cmp` 处于 `beta` 阶段，在 `v0.8.1` 中，补全有时弹不出来： [Some lsp will not show up after updating to v0.8.1](https://github.com/Saghen/blink.cmp/issues/718)

2024-12-22 12:20 UTC, wlh320 commented
> 注意 `blink.cmp` 处于 `beta` 阶段，在 `v0.8.1` 中，补全有时弹不出来： [Some lsp will not show up after updating to v0.8.1](https://github.com/Saghen/blink.cmp/issues/718)

我这边没法复现你的问题，应该是别的因素导致的。而且我感觉你跟 blink.cmp 提 issue 没什么用，这个 LSP 太小众了，而且影响因素很多，即使我都很难复现 issue 里的问题，他那边就更别提了。

2024-12-22 12:23 UTC, Kaiser-Yang commented
> > 注意 `blink.cmp` 处于 `beta` 阶段，在 `v0.8.1` 中，补全有时弹不出来： [Some lsp will not show up after updating to v0.8.1](https://github.com/Saghen/blink.cmp/issues/718)
> 
> 我这边没法复现你的问题，应该是别的因素导致的。而且我感觉你跟 blink.cmp 提 issue 没什么用，这个 LSP 太小众了，而且影响因素很多，即使我都很难复现 issue 里的问题，他那边就更别提了。

你用的什么方案？我这边`v0.8.1` 100%复现 https://gitee.com/kaiser-yang/rime-config/tree/kaiser-rime/

2024-12-22 12:25 UTC, Kaiser-Yang commented
nvim 补全配置主要在 [conifguration for blink-cmp](https://github.com/Kaiser-Yang/dotfiles/commit/9901e409c4ae61aae2cb49d99a613e48459eb74b) 的 `rime-ls.lua` 和 `cmpblink_config.lua`

2024-12-22 12:27 UTC, wlh320 commented
我用的我自己的方案和配置，所以我觉得应该先查一下我们这边的问题

2024-12-22 12:28 UTC, Kaiser-Yang commented
我感觉可能只有五笔可能触发

2024-12-22 12:37 UTC, Kaiser-Yang commented
blink 确实比 cmp 快多了。

2024-12-22 13:00 UTC, wlh320 commented
blink.cmp 升级会下载新的动态库，我这边有时候升级版本会有问题，建议你删除掉 `~/.local/share/nvim/lazy/blink.cmp` 然后重新安装试一下。或者你的 blink.cmp 的配置是不是有问题，可以删掉一部分重新试一下。我这边调成五笔还是没有复现。

2024-12-22 13:32 UTC, Kaiser-Yang commented
定位到了我删除 `auto-pairs` 后就对了，应该和 https://github.com/Saghen/blink.cmp/issues/714 这个问题有关。

2024-12-22 15:11 UTC, Kaiser-Yang commented
换了个插件后，现在的配置非常流畅：https://github.com/Kaiser-Yang/dotfiles/commit/99984310139f5095620c8c6cedb625a49cdb2223

2024-12-24 13:06 UTC, wlh320 requested changes
感谢提供相关配置。我再试用几天，没问题就合了，年内再发一个版本。

2024-12-24 13:06 UTC, wlh320 commented on doc/nvim-with-blink.md
> +-- auto upload when there is only one rime item after inputting a number
”upload“ 感觉意义不太符合，这里用 ”commit“比较好。cmp 的文档里似乎也有类似问题，之前没注意

2024-12-24 13:06 UTC, wlh320 commented on doc/nvim-with-blink.md
> +    local rime_item_index = get_n_rime_item_index(2, event.items)
```lua
    require('blink.cmp.completion.list').show_emitter:on(function(event)
      if #event.items ~= 1 then return end
      local col = vim.fn.col('.') - 1
      if event.context.line:sub(1, col):match("^.*%a+%d+$") == nil then return end
      local client = vim.lsp.get_client_by_id(event.items[1].client_id)
      if (not client) or client.name ~= "rime_ls" then return end
      require('blink.cmp').accept({ index = 1 })
    end)
```

这是我现在用的版本

2024-12-24 13:13 UTC, Kaiser-Yang commented on doc/nvim-with-blink.md
> +    local rime_item_index = get_n_rime_item_index(2, event.items)
> 没看懂修改这段的必要性。我之前写的在函数一开始判断长度不是 1 提前返回，我觉得效率更高一点。

输入时可能出现，rime候选只用一个，但有其他候选，例如buffer类型。

2024-12-24 13:19 UTC, Kaiser-Yang commented on doc/nvim-with-blink.md
> +    if event.context.line:sub(col, col):match("%d") == nil then return end
你说的这个问题不会发生，我在get_n_rime_item_index写了只有之前的输入是 `alphabet` 里面的才会接受，`2024.12.24` 输入完全正常。

2024-12-24 13:19 UTC, Kaiser-Yang commented on doc/nvim-with-blink.md
> +-- auto upload when there is only one rime item after inputting a number
这个你后面可以改一改。

2024-12-24 13:26 UTC, Kaiser-Yang commented on doc/nvim-with-blink.md
> +    if event.context.line:sub(col, col):match("%d") == nil then return end
如果你在这里遇到了问题，你需要根据你自己的方案去修改 rime_item_acceptable

2024-12-25 04:07 UTC, wlh320 commented on doc/nvim-with-blink.md
> +    local rime_item_index = get_n_rime_item_index(2, event.items)
有其他候选意味着此时有可能想输入其他东西，不是更不应该直接选中了吗？我认为配置示例应该简单地展示可以实现这种功能，不宜太过具体、复杂和完善。

2024-12-25 04:10 UTC, Kaiser-Yang commented on doc/nvim-with-blink.md
> +    local rime_item_index = get_n_rime_item_index(2, event.items)
你说的这种情况应该 toggle rime 再输入，真实输入时，也是用 shift 切换后输入。

2024-12-25 04:45 UTC, wlh320 commented on doc/nvim-with-blink.md
> +    local rime_item_index = get_n_rime_item_index(2, event.items)
在是否完全贴近输入法这块我发现我确实可能跟很多用户都有分歧。

我的想法是这既然是作为代码补全，就应该像补全一样只是提供一个参考和建议，由用户决定是否接受，而不是应该像输入法一样直接强行夺走用户的按键操作，要靠用户自己手动切换。像我这样基本什么都不配置会需要多按一些按键，但跟补全的形式更加一体。

后面那些五笔相关的功能配置我觉得很有用，也能帮助到很多用户。本身 vim 和 rime 用户就是定制化程度很高，特别多样化，什么需求的人都有。

我也不会强迫用户接受我的想法。我更愿意按我自己的想法写文档。我现在觉得更好的方案是描述完功能之后，贴上对应的配置链接，有需要的去你的仓库参考你的配置，在这个项目里的文档里就不保留太复杂的配置了，尽可能保持简单。同时想要复杂功能的也可以从其他人的代码得到参考。

当然写个插件让人开箱即用对我来说肯定是最好的选择，但这需要大量的时间和处理各种各样的不同需求。
我过段时间会总结一下相关的需求，重新写一下文档，如果有必要会单开一个插件的项目。

2024-12-25 05:58 UTC, merged